# Generated by Django 5.1.4 on 2024-12-27 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='The number of units of the product is in the cart')),
                ('product', models.ForeignKey(help_text='The product that has added to the cart', on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('user', models.ForeignKey(help_text='The User who added this to there shopping cart ', on_delete=django.db.models.deletion.CASCADE, related_name='cart_item', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
